version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/anirudh-deepsource/tools"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "shell"
enabled = true